# Generated by Django 2.0.5 on 2018-05-08 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=10)),
            ],
            options={
                'db_table': 'host_lists',
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'db_table': 'prospects',
                'ordering': ('name',),
            },
        ),
    ]
