name: notebooks
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pandas-profiling
  - geopandas
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - ipython
  - pip
  - pip:
    - git+https://github.com/myles/lazy-myles.git@main
