name: continuous deployment

on:
  push:
    branches:
    - main
    paths:
    - 'archive/**'

jobs:
  build-and-deploy-book:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository.
        uses: actions/checkout@v2

      - name: Cache conda stuff.
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Setup the conda environment.
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: notebooks
          environment-file: environment.yml
          auto-activate-base: true
          use-only-tar-bz2: true

      - name: Show some conda metadata.
        run: |
          conda info
          conda list
